### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by netzerospace** [narbehaj/ssl-checker#4]
i really like your tools, but i got this error while i scan

./ssl_checker.py -H www.brilife.co.id:443
+-------------------+
|Analyzing 1 host(s)|
+-------------------+
        [-] www.brilife.co.id    Failed: (-1, 'Unexpected EOF')
0 successful and 1 failed

whats wrong

**Comment by narbehaj** [comment]
Thanks @netzerospace I'm looking into it.

**Comment by narbehaj** [comment]
The new version has been updated with lots of improvements. Your issue is related to SSL bad configuration as mentioned [here](https://github.com/kennethreitz/requests/issues/3965#issuecomment-294214298) and it's not related to the ssl-checker script. Let me get into this deeply to handle the issue.
